version: '3'
services:
  db:
    image: mysql:5.7 
    container_name: chatbot_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=iii
    volumes:
      - ./Chatbot_Dev_cc103/mysql_data:/var/lib/mysql
      - ./Chatbot_Dev_cc103/mysql_init:/docker-entrypoint-initdb.d/
  api:
    image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/api:latest
    container_name: chatbot_api
    user: root
    environment:
      - GRANT_SUDO=yes
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./Chatbot_Dev_cc103/code:/home/jovyan/work/
    command: python /home/jovyan/work/code.py
  redis:
    image: redis:latest
    container_name: chatbot_redis
    volumes:
      - ./Chatbot_Line_cc103/redis/data:/data
  jupyter-tutorial:
    image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/jupyter:latest
    container_name: chatbot_line
    depends_on: 
      - api
      - redis
    command: python /home/jovyan/work/app.py
    volumes:
      - ./Chatbot_Line_cc103/code:/home/jovyan/work
  nginx-proxy:
    image: nginx:1.13.9
    container_name: chatbot_nginx
    depends_on:
      - jupyter-tutorial
    ports:
      - "443:443"
    volumes:
      - ./Chatbot_Line_cc103/docker_vol/nginx:/etc/nginx
      - ./Chatbot_Line_cc103/docker_vol/nginx-conf.d:/etc/nginx/conf.d
      - ./Chatbot_Line_cc103/docker_vol/cert-letsencrypt:/etc/pki/nginx


